{-
   Neurelo API Spec

   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI Version: 3.0.3
   Neurelo API Spec API version: 0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : NeureloAPISpec.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module NeureloAPISpec.Logging
  ( module NeureloAPISpec.LoggingKatip
  ) where

import NeureloAPISpec.LoggingKatip

#else

module NeureloAPISpec.Logging
  ( module NeureloAPISpec.LoggingMonadLogger
  ) where

import NeureloAPISpec.LoggingMonadLogger

#endif
